Repository likith1003/pull-A2, pull requests merged in 2025-05, with the labels that each got.

#2 :AS2
  subham.html
Labels: bug

#4 :AB monalisa
  monalisa.html
Labels: documentation

#6 :ABsarojinee
  sarojinee.html
Labels: documentation

#5 🆎
  Sarswat.html
Labels: enhancement

#7 :AB Amrita
  amrita.html
Labels: bug

#15 added kishan.html
  kishan.html
Labels: documentation

#14 🆎 Abhilipsa
  abhilipsa.html
Labels: documentation

#17 🆎 advesh
  advesh.html
Labels: enhancement

#18 :AB pradeep
  pradeep.html
Labels: enhancement

#11 :AB RashmiRanjan
  drashmin.html
Labels: good first issue

#19 nikhil added
  Nikhil.html
Labels: documentation, duplicate

#21 :AB punnya
  punnya.html
Labels: bug, documentation

#10 PM:created my page
  pankaj.html
Labels: documentation, invalid

#9 :Added_Code
  saswat.html
Labels: enhancement

#33 🆎 pankajini
  pankajini.html
Labels: documentation
